### ISSUE TITLE
LGDrawer  & LGButton

### ISSUE THREAD

**Issue by LindyLo** [Friend-LGA/LGFilterView#1]
LGDrawer  & LGButton Classes are missed

**Comment by Friend-LGA** [comment]
To try demo project you need to install cocoapods dependencies.
- Read and install cocoapods https://cocoapods.org/
- Run 'pod install' in terminal from 'Demo' directory (or just use script 'podsInstall.command')
- Use 'LGFilterViewDemo.xcworkspace' not 'LGFilterViewDemo.xcodeproj'

**Comment by romanr** [comment]
This is confusing because on project's home page screenshots show functionality that is not purely LGFilter but other components as well. Please add to documentation how to get whole thing working together without figuring out from demo.

**Comment by Friend-LGA** [comment]
LGFilterView is just table view with some hard coded animations to make it easy to use. Screenshots shows that you can achieve with this library. It is not obligatory to make design the same like in demo project and I don't see any reasons to add this quick example to documentation.
